### PR TITLE
Use date_floating on custom statuses

### PR DESCRIPTION
**Pull request by Absotively**
## Description
Mark PublishPress custom statuses as having floating dates, so that WordPress 5.3 or later won't automatically set dates on posts with PublishPress custom statuses.

Remove the workaround for WordPress' automatic date setting that was added for WordPress 5.3.

Add a WordPress version check to the pre-5.3 workaround so it's not applied in WordPress 5.3 or later.

## Benefits
Prevents unpublished posts with custom statuses from having their publication date set to when they were first saved. Unlike the current workaround, does not overwrite publication dates set by users.

## Possible drawbacks
Posts that were saved with custom statuses in WordPress 5.3 or later, while the workaround was in place, that have never had a publication date set by a user will not have their publication time changed to the current time when published. I don't know of any good way to tell such posts apart from posts that a user has set a publication date on.

Also, I haven't actually tested the version check on different versions of WordPress.

## Applicable issues
#741

## Checklist

- [x] I have created a specific branch for this pull request before committing, starting off the current HEAD of `development` branch. 
- [x] I'm submitting to the `development`, feature/hotfix/release branch. (Do not submit to the master branch!)
- [x] This pull request relates to a specific problem (bug or improvement).
- [x] I have mentioned the issue number in the pull request description text.
- [x] All the issues mentioned in this pull request relate to the problem I'm trying to solve.
- [x] The code I'm sending follows the [PSR-12](https://www.php-fig.org/psr/psr-12/) coding style.

### CODE REVIEW

**Comment by andergmartins** [comment]
Thanks @Absotively, we appreciate you taking the time for contributing.
It looks good at a first glance, but I will be able to finish reviewing and merging next week.

**Comment by Absotively** [comment]
Is there anything I can help with that's holding this up?

**Comment by SpencerDub** [comment]
@andergmartins I'm watching this PR with interest, as it affects my workflow as well. Absotively's fix would be much appreciated for our system.

**Review by andergmartins — APPROVED** [review]

**Comment by andergmartins** [comment]
Thanks, @Absotively, and sorry for the delay to merge this fix.

**Pull request merged**
